services:
  db:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_DB: memora
      POSTGRES_USER: memora
      POSTGRES_PASSWORD: memora
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U memora -d memora"]
      interval: 5s
      timeout: 3s
      retries: 10

  app:
    build:
      context: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/memora
      SPRING_DATASOURCE_USERNAME: memora
      SPRING_DATASOURCE_PASSWORD: memora
    ports:
      - "8080:8080"

volumes:
  dbdata:
